### ISSUE TITLE
Can't compile on Docker Toolbox edition

### ISSUE THREAD

**Issue by 0something0** [RhueOfL/fcw.org-server#1]
I attempted to run the freeciv web server using docker toolbox on the docker quickstart terminal, but the server refuses to compile with the error
```
Could not open requirements file: [Errno 2] No such file or directory: '/docker/requirements.txt'
ERROR: Service 'freeciv-web' failed to build: The command '/bin/sh -c 
DEBIAN_FRONTEND=noninteractive sudo apt-get update --yes --quiet &&  
DEBIAN_FRONTEND=noninteractive install/install.sh --mode=TEST &&
DEBIAN_FRONTEND=noninteractive sudo apt-get clean --yes &&     sudo rm --recursive --force /var/lib/apt/lists/*' returned a non-zero code: 1
``` 

I am running Windows 10 Home 64-bit Build 17134.

**Comment by andreasrosdal** [comment]
Try Vagrant.

**Comment by 0something0** [comment]
If docker isn't supported it might be a good idea to make that clear.

**Comment by RhueOfL** [comment]
You're right, we should remove docker until someone fixes it.

**Comment by RhueOfL** [comment]
I've removed and backed up the docker files and updated the readme.
